### ISSUE TITLE
Trackwork Causing VS engine to break. 1.20.1 Mod Ver 1.20.1-1.0.1

### ISSUE THREAD

**Issue by McArctic** [Endalion/trackwork#15] opened 2024-09-29 19:53 UTC
This does not full crash the server it just times EVERY one out. Unknown why this is happening at all. Will continue to look into it.

`[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: Error in physics pipeline background task
java.lang.NullPointerException: Cannot read field "trackPos" because "data" is null
    at edn.stratodonut.trackwork.tracks.data.PhysEntityTrackData.from(PhysEntityTrackData.java:60) ~[trackwork-1.20.1-1.0.1-beta.jar%23416!/:1.20.1-1.0.1-beta]
    at edn.stratodonut.trackwork.tracks.forces.PhysEntityTrackController.applyForcesAndLookupPhysShips(PhysEntityTrackController.java:64) ~[trackwork-1.20.1-1.0.1-beta.jar%23416!/:1.20.1-1.0.1-beta]
    at org.valkyrienskies.core.impl.shadow.Aq.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?]
    at org.valkyrienskies.core.impl.shadow.At.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?]
    at org.valkyrienskies.core.impl.shadow.Ap.run(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?]
    at org.valkyrienskies.core.impl.shadow.At$1.a(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?]
    at org.valkyrienskies.core.impl.shadow.At$1.invoke(Unknown Source) ~[valkyrienskies-120-2.3.0-beta.5.jar%23417!/:?]
    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) ~[kotlinforforge-4.11.0-all.jar%23366!/:?]
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!
[29Sep2024 03:23:36.188] [Physics thread/ERROR] [org.valkyrienskies.core.impl.shadow.Ap/]: !!!!!!! VS PHYSICS THREAD CRASHED !!!!!!!`

Full Log: https://api.mclo.gs/1/raw/DpYMm0B

**Comment by Endalion** [comment] 2024-10-13 07:48
duplicate of https://github.com/Endalion/trackwork/issues/12

**Closed by Endalion** 2024-10-13 07:48 UTC
Labels: duplicate
